inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Rails/HasManyOrHasOneDependent:
  Enabled: false